document.addEventListener("DOMContentLoaded",function(){const questions=document.querySelectorAll(".faq-accordion");let activeAnswer=null;let closeTimeout=null;questions.forEach((question)=>{const questionText=question.querySelector(".faq-question");const answer=question.querySelector(".faq-answer");questionText.addEventListener("click",function(e){e.stopPropagation();if(activeAnswer&&activeAnswer!==answer){activeAnswer.classList.remove("showAnswer");clearTimeout(closeTimeout)}
answer.classList.toggle("showAnswer");if(answer.classList.contains("showAnswer")){activeAnswer=answer;closeTimeout=setTimeout(()=>{if(activeAnswer){activeAnswer.classList.remove("showAnswer");activeAnswer=null}},3000)}else{activeAnswer=null;clearTimeout(closeTimeout)}})});document.addEventListener("click",function(){if(activeAnswer){activeAnswer.classList.remove("showAnswer");activeAnswer=null;clearTimeout(closeTimeout)}});var btnsAbrirPopup=document.querySelectorAll(".btn-abrir-popup"),overlay=document.querySelector(".overlay"),popup=document.querySelector(".popup"),btnCerrarPopup=document.getElementById("btn-cerrar-popup");const email={nombre:"",apellido:"",email:"",telefono:"",};const inputNombre=document.querySelector("#nombre");const inputApellido=document.querySelector("#apellido");const inputEmail=document.querySelector("#email");const inputPhone=document.querySelector("#phone");const formulario=document.querySelector("#registroForm");const btnSubmit=document.querySelector('#registroForm button[type="submit"]');const asistenciaError=document.querySelector("#asistencia-error");const asistenciaRadios=document.getElementsByName("asistencia_rompehielos");inputNombre.addEventListener("input",validar);inputApellido.addEventListener("input",validar);inputEmail.addEventListener("input",validar);inputPhone.addEventListener("input",validar);formulario.addEventListener("submit",validarAsistencia);asistenciaRadios.forEach((radio)=>radio.addEventListener("change",validarAsistencia));function validar(e){if(e.target.value.trim()===""){mostrarAlerta(`* Este campo es obligatorio`,e.target.parentElement);email[e.target.name]="";comprobarEmail();return}
if(e.target.id==="email"&&!validarEmail(e.target.value)){mostrarAlerta("* El email no es válido",e.target.parentElement);email[e.target.name]="";comprobarEmail();return}
limpiarAlerta(e.target.parentElement);email[e.target.name]=e.target.value.trim().toLowerCase();validarAsistencia(e);comprobarEmail()}
function validarAsistencia(e){let seleccionado=!1;for(let i=0;i<asistenciaRadios.length;i++){if(asistenciaRadios[i].checked){seleccionado=!0;break}}
if(!seleccionado){mostrarAlerta("* Por favor, confirme su asistencia al evento rompehielos.",asistenciaError);e.preventDefault()}else{limpiarAlerta(asistenciaError)}
comprobarEmail()}
function mostrarAlerta(mensaje,referencia){limpiarAlerta(referencia);const error=document.createElement("P");error.textContent=mensaje;error.classList.add("p-1","text-start","my-1","alerta-form");referencia.appendChild(error)}
function limpiarAlerta(referencia){const alerta=referencia.querySelector(".alerta-form");if(alerta){alerta.remove()}}
function validarEmail(email){const regex=/^\w+([.-_+]?\w+)*@\w+([.-]?\w+)*(\.\w{2,10})+$/;const resultado=regex.test(email);return resultado}
function comprobarEmail(){if(Object.values(email).includes("")||!asistenciaRadiosSeleccionado()){btnSubmit.disabled=!0;return}
btnSubmit.disabled=!1}
function asistenciaRadiosSeleccionado(){for(let i=0;i<asistenciaRadios.length;i++){if(asistenciaRadios[i].checked){return!0}}
return!1}});const slides=document.querySelector(".slides");const slideItems=document.querySelectorAll(".slide");const totalSlides=slideItems.length;const nextButton=document.querySelector(".next-button");const prevButton=document.querySelector(".prev-button");let currentIndex=0;function showSlide(index){const offset=-index*100;slides.style.transform=`translateX(${offset}%)`}
function nextSlide(){currentIndex=(currentIndex+1)%totalSlides;showSlide(currentIndex)}
function prevSlide(){currentIndex=(currentIndex-1+totalSlides)%totalSlides;showSlide(currentIndex)}
nextButton.addEventListener("click",nextSlide);prevButton.addEventListener("click",prevSlide);setInterval(nextSlide,5000);showSlide(currentIndex)