name: Node.js CI

on:
  push:
    branches:
      - main  # Cambia 'main' por tu rama principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Cambia la versión según tus necesidades

      - name: Install dependencies
        run: npm install

      - name: Run tests  # Opcional: Ejecutar pruebas si las tienes
        run: npm test

      - name: Start server
        run: npm start  # Asegúrate de que 'npm start' inicie tu servidor

      # Opcional: Puedes agregar pasos adicionales según sea necesario
