name: Node.js CI

on:
  push:
    branches:
      - main  # Cambia 'main' por tu rama principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x' # Cambia la versión según tus necesidades

      - name: Install dependencies
        run: npm install
        working-directory: scripts  # Ajusta la carpeta si es necesario

      - name: Run server.js
        run: node scripts/server.js  # Ajusta la ruta si es necesario

      # Opcional: Puedes agregar pasos adicionales según sea necesario
